name: Pull Request

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    name: Build and test with Node ${{ matrix.node-version }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js latest LTS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Restore packages
        run: npm ci

      - name: Restore local packages
        run: npm run install-local-packages

      - name: Run lint
        run: npm run lint

      - name: Build package
        run: npm run build
