name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release package to NPM
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Restore packages
        run: npm ci

      - name: Restore local packages
        run: npm run install-local-packages

      - name: Run lint
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Publish @makerx/eslint-config (if version has been updated)
        uses: JS-DevTools/npm-publish@v4
        with:
          package: 'packages/eslint/package.json'
          access: 'public'

      - name: Publish @makerx/prettier-config (if version has been updated)
        uses: JS-DevTools/npm-publish@v4
        with:
          package: 'packages/prettier/package.json'
          access: 'public'

      - name: Publish @makerx/ts-toolkit (if version has been updated)
        uses: JS-DevTools/npm-publish@v4
        with:
          package: 'dist/package.json'
          access: 'public'
          tag: 'beta'
